-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 06:50:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS DEFAULT CHARACTER SET utf8 ;
USE ;

-- -----------------------------------------------------
-- Table ``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farm_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farm_member` (
  `farm_id` INT NOT NULL AUTO_INCREMENT COMMENT '농가회원번호',
  `f_passwd` VARCHAR(20) NOT NULL COMMENT '농가 비밀번호',
  `f_email` VARCHAR(40) NOT NULL UNIQUE COMMENT '농가 이메일',
  `f_phonenum` char(11) NULL COMMENT '농가 휴대폰번호', 
  `f_name` VARCHAR(20) NOT NULL COMMENT '이름',
  `f_RRN` char(13) NULL COMMENT '농가 주민등록번호',
  `f_BRN` VARCHAR(13) NULL COMMENT '농가 사업자등록번호',
  `f_zipcode` INT NULL COMMENT '농가 우편번호',
  `f_location` VARCHAR(50) NULL COMMENT '농가 사업장소재지',
  `f_farm_name` VARCHAR(50) NULL COMMENT '농가이름',
  `f_num` VARCHAR(13) NULL COMMENT '농가전화번호',
  `f_explanation` VARCHAR(1000) NULL COMMENT '농가설명',
  `f_major_crop` VARCHAR(60) NULL COMMENT '농가 주요농작물',
  `f_profile_img` VARCHAR(200) NULL COMMENT '농가 프로필',
  `f_img` VARCHAR(200) NULL COMMENT '농가',
  `f_bank` VARCHAR(10) NULL COMMENT '농가 입금은행',
  `f_bank_name` VARCHAR(200) NULL COMMENT '농가 입금자명',
  `f_bank_num` BIGINT NULL COMMENT '농가 계좌번호',
  `f_bank_img` VARCHAR(200) NULL COMMENT '농가 통장사본',
  `authority` VARCHAR(10) NOT NULL DEFAULT 'ROLE_USER' COMMENT '사용자 권한',
  `token` VARCHAR(256) NULL COMMENT '토큰, 중복 로그인 확인용',
  PRIMARY KEY (`farm_id`)
);

-- -----------------------------------------------------
-- Table `consumer_member`
-- -----------------------------------------------------

--ERROR 1166 (42000): Incorrect column name 'authority '

CREATE TABLE IF NOT EXISTS `consumer_member` (
  `consumer_id` INT NOT NULL AUTO_INCREMENT COMMENT '소비자회원번호',
  `c_passwd` VARCHAR(20) NOT NULL COMMENT '소비자 비밀번호',
  `c_name` VARCHAR(10) NOT NULL COMMENT '소비자 이름',
  `c_email` VARCHAR(40) NOT NULL UNIQUE COMMENT '소비자 이메일',
  `c_phonenum` char(11) NOT NULL COMMENT '소비자 휴대폰번호',
  `c_zipcode` INT NULL COMMENT '소비자 우편번호',
  `c_location` VARCHAR(100) NULL COMMENT '소비자 주소',
  `c_profile_img` VARCHAR(200) NULL COMMENT '소비자 프로필사진',
  `user_authority` VARCHAR(10) NULL DEFAULT 'ROLE_USER' COMMENT '사용자 권한',
  `token` VARCHAR(256) NULL COMMENT '토큰, 중복 로그인 확인용',
  PRIMARY KEY (`consumer_id`)
  );

-- `token` VARCHAR(256) NULL COMMENT '토큰, 중복 로그인 확인용',
alter table consumer_member add token varchar (256);

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
  `product_id` INT NOT NULL AUTO_INCREMENT COMMENT '상품번호',
  `p_name` VARCHAR(50) NULL COMMENT '상품이름',
  `product` VARCHAR(20) NOT NULL COMMENT '작물명',
  `product_kg` INT NOT NULL COMMENT '중량',
  `p_drop_date` DATETIME NOT NULL COMMENT '낙과일자',
  `size` VARCHAR(5) NOT NULL COMMENT '크기',
  `p_status` VARCHAR(5) NOT NULL COMMENT '상태',
  `p_explanation` VARCHAR(200) NULL COMMENT '작물설명',
  `product_img_name` VARCHAR(200) NULL COMMENT '작물(사진)',
  `p_reg_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`product_id`)
  );

ALTER TABLE product ALTER column p_reg_date SET DEFAULT CURRENT_TIMESTAMP;
 

--   `p_max_price` INT NOT NULL,

-- -----------------------------------------------------
-- Table `auction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction` (
  `auction_Id` INT NOT NULL AUTO_INCREMENT COMMENT '경매번호',
  `auction_name` varchar(200) NOT Null COMMENT '경매이름',
  `start_date` DATETIME NOT NULL COMMENT '시작일',
  `deadline_date` DATETIME NOT NULL COMMENT '마감일',
  `a_starting_price` INT NOT NULL COMMENT '시작가격',
  `a_max_price` INT NOT NULL COMMENT '최대가격',
  `bid_price` INT NULL COMMENT '입찰가',
  `bid_num` INT NULL DEFAULT 0 COMMENT '입찰수',
  `bid_status` INT NULL COMMENT '경매상태',
  `bid_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입찰시간',
  `payment_status` TINYINT(1) NULL DEFAULT 0 COMMENT '결재 상태',
  PRIMARY KEY (`auction_Id`))
ENGINE = InnoDB
COMMENT = '	';



-- -----------------------------------------------------
-- Table `alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alert` (
  `alert_id` INT NOT NULL AUTO_INCREMENT COMMENT '알림번호',
  `d_status` TINYINT NOT NULL COMMENT '상태',
  `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '시간',
  `checked` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '알림 확인 여부',
  PRIMARY KEY (`alert_id`)
  );


--상태
-- 경매 시작 1
-- 입찰 알림 2
-- 입찰했는데 딴 사람이 입찰시 3
-- 입찰 한 경매 종료시 4 
-- 경매 종료 후 리뷰 썼을 시 5
-- 경매가 취소됐을 시 6

------------------------------------------------------------------------------

-- -----------------------------------------------------
-- Table `delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery` (
  `delivery_id` INT NOT NULL AUTO_INCREMENT COMMENT '배송번호',
  `d_status` TINYINT NOT NULL COMMENT '상태',
  `departure_date` DATETIME NULL COMMENT '출발일',
  `arrival_date` DATE NULL COMMENT '도착예정일',
  `zipcode` INT(11) NULL COMMENT '우편번호',
  `destination` VARCHAR(100) NULL COMMENT '목적지',
  PRIMARY KEY (`delivery_id`)
);


-- -----------------------------------------------------
-- Table `customer_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer_center` (
  `inquiry_id` INT NOT NULL AUTO_INCREMENT COMMENT '문의번호',
  `title` VARCHAR(50) NOT NULL COMMENT '문의제목',
  `content` VARCHAR(400) NOT NULL COMMENT '문의내용',
  `inquiry_date` DATETIME NOT NULL COMMENT '문의날짜',
  PRIMARY KEY (`inquiry_id`)
  );


-- -----------------------------------------------------
-- Table `auction_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_review` (
  `grade_point` TINYINT NOT NULL COMMENT '평점',
  `review` VARCHAR(200) NOT NULL COMMENT '후기'
);

-- -----------------------------------------------------
-- Table `grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grade` (
  `grade_id` INT NOT NULL COMMENT '등급번호',
  `grade` INT NOT NULL COMMENT '등급',
  `cumulative_amount` INT NOT NULL COMMENT '누적금액',
  `reserve_amount` INT NOT NULL COMMENT '적립금',
  PRIMARY KEY (`grade_id`)
);

-- -----------------------------------------------------
-- Table `search_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `search_word`  (
  `search_word_id` INT NOT NULL AUTO_INCREMENT COMMENT '검색어 번호',
  `keyword` VARCHAR(20) NOT NULL COMMENT '검색어',
  `date` DATETIME NOT NULL DEFAULT NOW() COMMENT '검색 시간',
  `ip` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '검색어 친 사람 ip',
  `consumer_id` INT NULL COMMENT '소비자회원번호',
  `farm_id` INT NULL COMMENT '농가회원번호',
PRIMARY KEY (`search_word_id`),
FOREIGN KEY(`consumer_Id`) REFERENCES consumer_member(consumer_id),
FOREIGN KEY(`farm_id`) REFERENCES farm_member(farm_id)
);

-- -----------------------------------------------------
-- Table `wish`
-- -----------------------------------------------------
CERATE TABLE IF NOT EXISTS `wish` (
  `auction_id` INT NULL COMMENT '경매번호',
  `consumer_id` INT NULL COMMENT '소비자회원번호',
  FOREIGN KEY(`auction_Id`) REFERENCES consumer_member(auction_id),
  FOREIGN KEY(`consumer_Id`) REFERENCES consumer_member(consumer_id),
)

-- -----------------------------------------------------
-- Table `payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment`  (
  `payment_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '주문 번호',
  `auction_Id` INT(11) NOT NULL COMMENT '경매 번호',
  `payment_amount` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '결제 금액',
  `pay_method` VARCHAR(20) NOT NULL DEFAULT 'card' COMMENT '결제 수단',
PRIMARY KEY (`payment_id`),
FOREIGN KEY(`auction_Id`) REFERENCES auction(auction_Id)
);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

------------------------------------------------------------------------------------
---------------------------테이블 관계 추가 -----------------------------------------
------------------------------------------------------------------------------------

-- 상품 관계
ALTER TABLE product add farm_id INT;
ALTER TABLE product add FOREIGN KEY(farm_id) REFERENCES farm_member(farm_id);


-- 경매 관계
ALTER TABLE auction add product_id INT;
ALTER TABLE auction add FOREIGN KEY(product_id) REFERENCES product(product_id);

ALTER TABLE auction add farm_id INT;
ALTER TABLE auction add FOREIGN KEY(farm_id) REFERENCES farm_member(farm_id);

--알림 관계
ALTER TABLE alert add auction_Id INT;
ALTER TABLE alert add FOREIGN KEY(auction_Id) REFERENCES auction(auction_Id);

ALTER TABLE alert add consumer_id INT;
ALTER TABLE alert add FOREIGN KEY(consumer_Id) REFERENCES consumer_member(consumer_Id);

-- --검색 관계
-- ALTER TABLE search_word add FOREIGN KEY(consumer_Id) REFERENCES consumer_member(consumer_Id);
-- ALTER TABLE search_word add FOREIGN KEY(farm_id) REFERENCES farm_member(farm_id);


-- 경매횟수 컬럼 추가
-- alter table `consumer_member` add `count_auction` INT(11) default 0;
-- alter table `farm_member` add `count_auction` INT(11) default 0;

--경매 소비자
-- ?

--배송 관계
-- 농가, 상품, 경매, 소비자

--경매 후기
-- 경매 있을수도, 없을수도

--등급 관계
--농가, 소비자

--고객센터
-- 따로

--농가 test data
insert into farm_member (farm_id, f_email, f_passwd, f_phonenum, f_name) values ('1', '111@111.com', '111111', '01011111111', '1번이오');
insert into farm_member (farm_id, f_email, f_passwd, f_phonenum, f_name) values ('2', '222@222.com', '222222', '01022222222', '2번이오');

alter table farm_member modify f_phonenum char (11);
alter table farm_member modify f_RRN char (13);
alter table farm_member modify f_BRN varchar (13);

`auction_name` varchar(200) NOT Null COMMENT '경매이름',

alter table auction add (auction_name varchar(200) not null DEFAULT '1');

alter table farm_member modify f_bank_num bigint;

alter table consumer_member modify c_passwd varchar(256);
alter table farm_member modify f_passwd varchar(256);


alter table consumer_member CHANGE user_authority authority VARCHAR(10);